### ISSUE TITLE
System.Net.WebException was unhandled by user code

### ISSUE THREAD

**Issue by ErikHumphrey** [FabianTerhorst/GW2AccountViewer#1]
```
System.Net.WebException was unhandled by user code
  HResult=-2146233079
  Message=The remote server returned an error: (400) Bad Request.
  Source=System
  StackTrace:
       at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
       at GW2AccountViewer.GW2AccounViewerApplication.parseAccount(IAsyncResult result) in C:\Users\Cronos\Documents\GW2AccountViewer-master\GW2AccounViewerApplication.cs:line 613
       at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
       at System.Net.ContextAwareResult.CompleteCallback(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Net.ContextAwareResult.Complete(IntPtr userToken)
       at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
       at System.Net.HttpWebRequest.ProcessResponse()
  InnerException: 

```

**Comment by FabianTerhorst** [comment]
The access token for the api is invalid. You have to replace him with your own key. https://github.com/FabianTerhorst/GW2AccountViewer/blob/15b0690d9fdcd609a066848092096147a1dea5a8/GW2AccounViewerApplication.cs#L481
